name: Maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-checks:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: "s"
        run: |
          python -m pip install --upgrade pip
          pip install --editible '.[scraper]'
      - run: cd scripts && ./scrape_checks.py
