name: Test

on:
  push:
    branches-ignore:
      - main

env:
  # GitHub Actions Runner is not a tty therefore lots of tools disable colour
  # The webview supports ANSI colour so we try to add colour support here
  #| env var                         | supported by      |
  FORCE_COLOR: "true"                # nox,pip
  PYTEST_ADDOPTS: "--color=yes"      # pytest
  PRE_COMMIT_COLOR: "always"         # pre-commit

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - run: python -m pip install --upgrade --no-input nox
      - name: test
        run: python -Im nox --python ${{matrix.python-version}}
